feat: #WB-1985, create image extension
opendigitaleducation/rte-content-converter pull request #16
Opened 2023-11-27 17:07 UTC by Headan

2023-11-28 07:16 UTC, jcbe-ode requested changes

2023-11-28 07:16 UTC, jcbe-ode commented on packages/extension-image/src/image.ts
> +      href: {
Un attribut href pour le tag <img> ?

Plus globalement, il serait intéressant d'ajouter en début de fichier un exemple de tag <img> avec tous les attributs supportés par l'extension (=notre modèle de doc riche pour les images)

2023-11-28 07:16 UTC, jcbe-ode commented on package.json
> +    "@tiptap/extension-image": "^2.1.12",
Fixer le n° de version comme ailleurs (2.0.3 il me semble)

2023-11-30 17:31 UTC, ccreusat commented on packages/extension-image/src/image.ts
> +  name: 'custom-image',
@Headan si le nom de ton extension s'appelle "custom-image" alors ta const aussi `const CustomImage`

2023-12-05 08:44 UTC, merged