feat: #WB-1993, create new extension attachment
opendigitaleducation/rte-content-converter pull request #7
Opened 2023-09-14 15:15 UTC by Headan

Ajout d'une nouvelle extension Attachment.

Ticket : #WB-1993
https://edifice-community.atlassian.net/browse/WB-1993

2023-09-15 15:46 UTC, jcbe-ode requested changes
Beau travail ! Les extensions TipTap, c'est touffu au premier abord et pas toujours bien documenté, mais qu'est-ce que c'est puissant !

J'ai ajouté quelques commentaires nécessitant, je pense, de petits changements.
Et restera à valider la partie Thumbnails avant implémentation (voir ticket et commentaires)

2023-09-15 15:46 UTC, jcbe-ode commented on packages/extension-attachment/README.md
> +# extension-typosize
A mettre à jour : 

```
# extension-typosize
...
A Tiptap extension that attaches external resources (id, description, content-type and thumbnails if any)  into/from rich text content.
```

2023-09-15 15:46 UTC, jcbe-ode commented on packages/extension-attachment/src/Attachment.ts
> +          return documentId;
Cette extension doit pouvoir parser l'ancien format des pièces jointes (ça me semble ok) et générer le nouveau format,
mais elle doit aussi pouvoir parser le nouveau format !

=> A priori, il doit falloir gérer ici l'attribut `data-document-id`.
Toute valeur trouvée serait alors prioritaire sur un éventuel `<a href="/workspace/document/id-de-document-dans-url">`

2023-09-15 15:46 UTC, jcbe-ode commented on packages/extension-attachment/src/Attachment.ts
> +          return { 'data-content-type': attributes.dataContentType };
Cet attribut est optionnel, et peut ne pas exister du tout. Est-ce bien géré ?

2023-09-15 15:46 UTC, jcbe-ode commented on packages/extension-attachment/src/Attachment.ts
> +          return { 'data-content-type': attributes.dataContentType };
_TODO_ : parse + render des `<thumbnail>` (voir ticket).
_TODO_ : vérifier si Guillaume a relu le cadrage tech et si c'est ok pour lui.

Les miniatures (<thumbnail>) sont optionnelles, mais il peut en exister plusieurs pour chaque pièces jointe.
Elles sont modélisées dans le contenu riche par des balises `<thumbnail>` , avec des metadata **resolution** `largeur x hauteur` et **ID de document**

On ne retiendra qu'un seul thumbnail pour chaque résolution => s'il y a 2 thumbnails "64x64", on ne conservera qu'un seul des deux dans le `render`.

Le composant React qui affichera les PJs pourra exploiter l'un ou plusieurs des thumbnails.
Côté mobile,  le thumbnail utilisé sera le plus proche de la taille idéale.

2023-09-18 14:20 UTC, Headan commented on packages/extension-attachment/src/Attachment.ts
> +          return { 'data-content-type': attributes.dataContentType };
> Cet attribut est optionnel, et peut ne pas exister du tout. Est-ce bien géré ?

Alors ca ne pose pas de problème quand l'attribut n'est pas présent, l'attribut n'est juste pas générer mais je peux mettre une valeur par défaut mais je trouve que ça n'a pas trop de sens

2023-09-20 08:43 UTC, Headan commented on packages/extension-attachment/src/Attachment.ts
> +          return { 'data-content-type': attributes.dataContentType };
@jcbe-ode Du coup j'ai avec @ccreusat pour les thumbnails. On en a besoin côté mobile mais pas côté web du coup dans un premier temps je laisse le parser qui fonctionne bien sur les thumbnails et pour le parser on verra si c'est utile ou pas plus tard 😄

2023-09-21 08:33 UTC, jcbe-ode commented on packages/extension-attachment/src/Attachment.ts
> +          return { 'data-content-type': attributes.dataContentType };
Les extensions TipTap vont définir le modèle (la syntaxe) de nos documents riches.
=> Il faut absolument éviter de les modifier après la MEP car sinon, on devra gérer plusieurs versions des extensions modifiées, afin que le backend puisse effectuer les migrations de données en utilisant la version adéquate.
==> je préfèrerais que les extensions soient 100% finies avant la MEP.

Donc pas de soucis pour merger ta PR, si en l'état elle permet de dérouler les développements, mais il faut en // créer un ticket "Compléter la gestion des balises thumbnails" afin de ne pas oublier d'y revenir dessus plus tard (toi ou un autre dev, peu importe).

2023-09-21 08:34 UTC, jcbe-ode approved these changes

2023-09-22 07:39 UTC, merged